### ISSUE TITLE
could you give me a link download in China

### ISSUE THREAD

**Issue by souleater06** [Jarvis-Yu/Dottore-Genius-Invokation-TCG-Simulator#10]

**Comment by Jarvis-Yu** [comment]
You mean the repository? I assume if you can raise an issue, you can fork/clone the repository. If not, please reply.

**Comment by souleater06** [comment]
hey guys，there are plenty of companys finding this kind of opptunities of tcg in China。你应该是国人吧，加我微信聊聊。13265145261



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 6, 2023 17:09 PM
To: ***@***.***&gt;;
Cc: "john ***@***.******@***.***&gt;;
Subject: Re: [Jarvis-Yu/Dottore-Genius-Invokation-TCG-Simulator] could yougive me a link download in China (Issue #10)




 
You mean the repository? I assume if you can raise an issue, you can fork/clone the repository. If not, please reply.

**Comment by Jarvis-Yu** [comment]
加陌生人我一般用QQ，你留QQ号吧。

**Comment by souleater06** [comment]
> 加陌生人我一般用QQ，你留QQ号吧。

1990732037

**Comment by souleater06** [comment]
iwill delect later

**Comment by Jarvis-Yu** [comment]
u may delete now
