### ISSUE TITLE
Create detailed milestone files and link them in README

### ISSUE THREAD

**Issue by Jarvis-Yu** [Jarvis-Yu/Dottore-Genius-Invokation-TCG-Simulator#11]
There needs to be some milestone files containing the progress on cards and characters.

You should probably create the path `readme/milestones/`

Create two markdown files "cards_milestone.md" and "characters_milestone.md", each containing the progress on each character/card using a similar style as in "README.md" milestones section.

Refer to https://genshin-impact.fandom.com/wiki/Genius_Invokation_TCG/Card_List to find the list of all available cards. (note that we only want to implement cards obtainable by players for now)

If you have any questions regarding on the actual progress of the cards/characters, contact Jarvis-Yu, the repo owner.

Check [wiki](https://github.com/Jarvis-Yu/Dottore-Genius-Invokation-TCG-Simulator/wiki) for code/commit style guide.

**Comment by viktoriussuwandi** [comment]
Hi [Jarvis-Yu](https://github.com/Jarvis-Yu), May I contribute to this issue ?

**Comment by Jarvis-Yu** [comment]
Sure, just fork the repo and make a pull request, appreciate your help.

**Comment by viktoriussuwandi** [comment]
Thanks [Jarvis-Yu](https://github.com/Jarvis-Yu)

**Comment by Jarvis-Yu** [comment]
No longer needed
