### ISSUE TITLE
translate Shell scripts to Powershell scripts needed

### ISSUE THREAD

**Issue by Jarvis-Yu** [Jarvis-Yu/Dottore-Genius-Invokation-TCG-Simulator#17]
Currently, in the `scripts/` folder, there are some `.sh` scripts for shell, and some `.ps1` scripts for powershell.

Unfortunately, the `.ps1` scripts are out-dated, but the `.sh` ones are up-to-date.

Please translate `cli.sh`, `test.sh`, `venv.sh`, `profile.sh` and `build.sh` to corresponding `.ps1` files. If there existed `.ps1` file with the same name, overwrite them.

Don't be afraid, all scripts are very short, with just a few lines.

Once scripts are written, please try run them yourself before creating a *Pull Request*.

(Optionally, you may move all `.sh` scripts to `scripts/sh/` and `.ps1` scripts to `scripts/ps1/`)

**Comment by nandofromthebando** [comment]
Just finished it up!

**Comment by Jarvis-Yu** [comment]
> Just finished it up!
> 
> 

Awesome, if you don't mind, can you also update the 'For Windows based systems' section in 'docs/dev_readme.md' on how to use the updated scripts as well? Thanks a lot.

**Comment by Jarvis-Yu** [comment]
I'm not even sure about how to run one in powershell... so I need your help

**Comment by Jarvis-Yu** [comment]
If that's too much for u, then please leave a note. I'll review the PR tonight and update the README myself later.

**Comment by nandofromthebando** [comment]
Might be a little too much for me sorry but I'll check out the README when you update it so I can learn from now on thank you! I hope that I could be of some help!

**Comment by Jarvis-Yu** [comment]
Understood, appreciate your help! I'll have a look at the PR tonight.

**Comment by nandofromthebando** [comment]
Thank you!
