### ISSUE TITLE
Bennett's "Inspiration Field" In The Simulator Does Not Match Its Performance In Actual Gameplay

### ISSUE THREAD

**Issue by Senoras** [Jarvis-Yu/Dottore-Genius-Invokation-TCG-Simulator#31]
Bennett's Inspiration Field healing effect targets the character who used the skill, not the currently active character. 

This means if the active character is switched before Inspiration Field takes effect, such as using the elemental skill of Kazuha or the card Wind and Freedom, it will still heal the character who used the skill, rather than the new active character.

**Comment by Senoras** [comment]
Expected tags: Bug, Easy, Middle Priority.

**Comment by Senoras** [comment]
Expected tags: Bug, Easy, Medium-Priority

**Comment by Jarvis-Yu** [comment]
Fixed in commit 22a4213
