### ISSUE TITLE
The Logic of the POST_DMG Signal Does Not Accurately Reflect the Actual Game Behavior

### ISSUE THREAD

**Issue by Senoras** [Jarvis-Yu/Dottore-Genius-Invokation-TCG-Simulator#33]

**Comment by Senoras** [comment]
Expected tags: Enhancement, Hard, Low-Priority

**Comment by Senoras** [comment]
By the way, I'm not sure which word, "requirement" or "request," is more appropriate.

**Comment by Jarvis-Yu** [comment]
Imo, as an issue, simply stating the problem should be enough.

e.g.

"The Logic of the POST_DMG Signal Does Not Accurately Reflect the Actual Game Behavior"

**Comment by Senoras** [comment]
True.

**Comment by Jarvis-Yu** [comment]
All POST_DMG signals should have now been fixed after 3bbc22bbef5e71093ea284ebaa2440fbb12f0ba8.
